{
(** The Nix lexer, generated by ocamllex.

    Generated rather than hand-written for the reason recorded in
    [docs/decisions/2026-08-02-nix-frontend-build-not-reuse.md]: Nix's own
    lexer is Flex, its tokens overlap, and maximal munch is what resolves them.
    The sharpest case is [x:x], which is a URI and NOT a lambda, because the
    URI rule matches more characters than [ID] does. A hand-written tokeniser
    that reads an identifier and then a colon disagrees with Nix silently.

    Interpolation needs lexer STATE, exactly as Nix's start conditions do:
    inside a string, [${] switches back to expression lexing, and the matching
    [}] has to be told apart from an attribute set's closing brace. That is
    what {!stack} is for. *)

open Parser

exception Error of string * Lexing.position

let error lexbuf msg = raise (Error (msg, Lexing.lexeme_start_p lexbuf))

(** What the lexer is in the middle of. The [}] token is ambiguous without it:
    it closes an attribute set in [Expr] and ends an antiquotation otherwise. *)
type state = Expr | In_string | In_ind_string

let stack : state list ref = ref [Expr]
let push s = stack := s :: !stack
let pop () = match !stack with _ :: t when t <> [] -> stack := t | _ -> ()
let top () = match !stack with s :: _ -> s | [] -> Expr

let reset () = stack := [Expr]

let buf = Buffer.create 256

(** The five escapes a Nix string understands, plus [\${] which is how an
    interpolation is escaped. *)
let unescape c =
  match c with
  | 'n' -> '\n'
  | 'r' -> '\r'
  | 't' -> '\t'
  | c -> c
}

let digit = ['0'-'9']
let alpha = ['a'-'z' 'A'-'Z']
let id_start = alpha | '_'
let id_char = alpha | digit | '_' | '\'' | '-'
let id = id_start id_char*
let int = digit+
let float =
  (digit+ '.' digit* | '.' digit+) (['E' 'e'] ['+' '-']? digit+)?
let path_char = alpha | digit | ['.' '_' '+' '-']
let path = path_char* ('/' path_char+)+ '/'?
let hpath = '~' ('/' path_char+)+ '/'?
let spath = '<' path_char+ ('/' path_char+)* '>'
let uri_scheme = alpha (alpha | digit | ['+' '-' '.'])*
let uri_char =
  alpha | digit | ['%' '/' '?' ':' '@' '&' '=' '+' '$' ',' '_' '.' '!' '~' '*'
                   '\'' '-']
let uri = uri_scheme ':' uri_char+

rule token = parse
  | [' ' '\t' '\r']+ { token lexbuf }
  | '\n' { Lexing.new_line lexbuf; token lexbuf }
  | '#' [^ '\n']* { token lexbuf }
  | "/*" { comment lexbuf }

  (* Keywords before `id`, and `uri` before both, so maximal munch decides. *)
  | uri as s { URI s }
  | "if" { IF }
  | "then" { THEN }
  | "else" { ELSE }
  | "assert" { ASSERT }
  | "with" { WITH }
  | "let" { LET }
  | "in" { IN }
  | "rec" { REC }
  | "inherit" { INHERIT }
  | "or" { OR_KW }
  | id as s { ID s }

  | float as s { FLOAT (float_of_string s) }
  | int as s { INT (int_of_string s) }
  | path as s { PATH s }
  | hpath as s { PATH s }
  | spath as s { SPATH (String.sub s 1 (String.length s - 2)) }

  | '"' { push In_string; DQUOTE }
  | "''" { push In_ind_string; IND_OPEN }

  | "${" { push Expr; DOLLAR_CURLY }
  | '{' { push Expr; LCURLY }
  | '}' {
      match top () with
      | Expr -> pop (); RCURLY
      | _ -> error lexbuf "unbalanced '}'"
    }

  | '(' { LPAREN }
  | ')' { RPAREN }
  | '[' { LBRACK }
  | ']' { RBRACK }
  | ';' { SEMI }
  | ',' { COMMA }
  | ':' { COLON }
  | '@' { AT }
  | '.' { DOT }
  | "..." { ELLIPSIS }
  | '?' { QUESTION }
  | "==" { EQ }
  | "!=" { NEQ }
  | "<=" { LEQ }
  | ">=" { GEQ }
  | "&&" { AND }
  | "||" { OR }
  | "->" { IMPL }
  | "//" { UPDATE }
  | "++" { CONCAT }
  | '=' { ASSIGN }
  | '<' { LT }
  | '>' { GT }
  | '+' { PLUS }
  | '-' { MINUS }
  | '*' { TIMES }
  | '/' { SLASH }
  | '!' { NOT }
  | eof { EOF }
  | _ as c { error lexbuf (Printf.sprintf "unexpected character %C" c) }

and comment = parse
  | "*/" { token lexbuf }
  | '\n' { Lexing.new_line lexbuf; comment lexbuf }
  | eof { error lexbuf "unterminated comment" }
  | _ { comment lexbuf }

(* A double-quoted string. Returns one STR chunk at a time; the parser
   assembles them, so an interpolation is just a token in the middle. *)
and string_part = parse
  | '"' { pop (); DQUOTE }
  | "${" { push Expr; DOLLAR_CURLY }
  | "\\${" { STR "${" }
  | '\\' (_ as c) { STR (String.make 1 (unescape c)) }
  | '\n' { Lexing.new_line lexbuf; STR "\n" }
  | [^ '"' '\\' '$' '\n']+ as s { STR s }
  | '$' { STR "$" }
  | eof { error lexbuf "unterminated string" }

(* An indented string. The dedenting that Nix applies is deliberately NOT done
   here: it is a property of the whole literal, so it belongs to the parser
   action that has all the parts. *)
and ind_string_part = parse
  | "''" { pop (); IND_CLOSE }
  | "${" { push Expr; DOLLAR_CURLY }
  | "'''" { STR "''" }
  | "''$" { STR "$" }
  | "''\\" (_ as c) { STR (String.make 1 (unescape c)) }
  | '\n' { Lexing.new_line lexbuf; STR "\n" }
  | [^ '\'' '$' '\n']+ as s { STR s }
  | '\'' { STR "'" }
  | '$' { STR "$" }
  | eof { error lexbuf "unterminated indented string" }

{
(** The entry point menhir drives: dispatch on the state stack, so the same
    token stream carries expressions and string chunks. *)
let read lexbuf =
  match top () with
  | Expr -> token lexbuf
  | In_string -> string_part lexbuf
  | In_ind_string -> ind_string_part lexbuf
}
