(** The Nix language front-end: parse a `.nix` file to an {!Ast.t}.

    The parser is generated by menhir from [parser.mly] and the lexer by
    ocamllex from [lexer.mll], per
    [docs/decisions/2026-08-02-nix-frontend-build-not-reuse.md]. *)

exception Error of string

(** Parse Nix source. *)
let parse_string ?(base = "") ?(home = "") (src : string) :
    (Ast.t, string) result =
  Lexer.reset () ;
  (* Nix resolves relative paths against the directory of the file being
     parsed, so a caller that has a real file must say where it came from. *)
  Ast.base_dir := base ;
  Ast.home_dir := home ;
  let lexbuf = Lexing.from_string src in
  try Ok (Parser.main Lexer.read lexbuf) with
  | Lexer.Error (msg, pos) ->
      Error
        (Printf.sprintf
           "%d:%d: %s"
           pos.pos_lnum
           (pos.pos_cnum - pos.pos_bol + 1)
           msg)
  | Parser.Error ->
      let pos = Lexing.lexeme_start_p lexbuf in
      Error
        (Printf.sprintf
           "%d:%d: syntax error"
           pos.pos_lnum
           (pos.pos_cnum - pos.pos_bol + 1))

(** Parse and print in [nix-instantiate --parse] form, which is what the
    differential test compares. *)
let parse_and_print ?(base = "") ?(home = "") (src : string) :
    (string, string) result =
  Result.map Printer.to_string (parse_string ~base ~home src)
