//! The Nix EXPRESSION layer: write Nix in Rust, print `.nix`.
//!
//! This is the second of the two term algebras in `docs/architecture.md`. The
//! rest of the crate is the FIRST-ORDER one (derivations, ATerm, store paths);
//! this module is the SECOND-ORDER one, because Nix expressions have binders
//! and derivations do not.
//!
//! It depends on the rest of the crate and the rest never depends on it, which
//! is the rule that keeps a bug in the expression layer from being able to
//! change a store path.
//!
//! Nothing here needs a parser. The transpiler is only the arrow `EXPR ->
//! .nix`, so it is [`ast`], [`emit`] and [`surface`] alone; LALRPOP arrives
//! with the arrow the other way and is not a dependency of this module.

pub mod ast;
pub mod emit;
pub mod lexer;
pub mod mk;
pub mod normalize;
pub mod paths;
pub mod printer;
pub mod strings;
pub mod surface;
pub mod transpile_examples;
pub mod worked_example;

// Generated by LALRPOP at build time from `grammar.lalrpop`. The path is
// relative to OUT_DIR and mirrors the source tree, so the module lands at
// `nix::grammar`.
lalrpop_util::lalrpop_mod!(
    #[allow(clippy::all, missing_docs, unused_parens, clippy::pedantic)]
    pub grammar,
    "/nix/grammar.rs"
);

pub use ast::Expr;
pub use emit::to_nix;

/// Parse Nix source into an AST.
///
/// `base` and `home` are what relative and tilde paths resolve against,
/// because Nix performs that resolution at PARSE time.
pub fn parse(source: &str, base: &str, home: &str) -> Result<Expr, String> {
    paths::set_context(base, home);
    grammar::MainParser::new()
        .parse(lexer::Lexer::new(source))
        .map_err(|e| format!("{e}"))
}

/// Parse, then print in `nix-instantiate --parse` form.
pub fn parse_and_print(source: &str, base: &str, home: &str) -> Result<String, String> {
    parse(source, base, home).map(|e| printer::to_parse_form(&e))
}
