// Code generated by goyacc -o /tmp/grammar.go -p nix grammar.y. DO NOT EDIT.

//line grammar.y:2
// The Nix grammar, for goyacc.
//
// Transcribed from NixOS/nix src/libexpr/parser.y at commit a86a3638. goyacc IS
// yacc, so this is the closest of the four to Nix's own file: the precedence
// block below is the same twelve levels, in the same order and the same syntax,
// as parser.y:208-219.
//
// Two of them surprise everyone, and getting either wrong changes what real
// files MEAN rather than failing to parse them:
//
//   - `!` sits BELOW `+`, so `!a + b` is `!(a + b)`;
//   - `//` sits ABOVE the comparisons, so `a // b == c` is `(a // b) == c`.
//
// Both are checked against nix-instantiate --parse.
//
// The generated parser is COMMITTED, because Go has no build step to run a
// generator in. That makes grammar.go the only generated table in this
// repository that a reviewer can read, and the only one that can go stale; the
// Makefile's generate-parser target and a CI check keep it honest.

package nix

import __yyfmt__ "fmt"

//line grammar.y:22

//line grammar.y:26
type nixSymType struct {
	yys     int
	num     int64
	fnum    float64
	str     string
	expr    Expr
	exprs   []Expr
	part    Part
	iparts  []indexedPart
	attr    Attr
	attrs   []Attr
	path    AttrPath
	binds   []Binding
	pattern Pattern
	formal  Formal
	formals []Formal
	parts   []Part
}

const INT = 57346
const FLOAT = 57347
const IDENT = 57348
const STR = 57349
const ESTR = 57350
const PATH = 57351
const SPATH = 57352
const URI_LIT = 57353
const PATH_START = 57354
const PATH_STR = 57355
const PATH_END = 57356
const IF = 57357
const THEN = 57358
const ELSE = 57359
const ASSERT = 57360
const WITH = 57361
const LET = 57362
const IN = 57363
const REC = 57364
const INHERIT = 57365
const OR_KW = 57366
const DQUOTE = 57367
const IND_OPEN = 57368
const IND_CLOSE = 57369
const DOLLAR_CURLY = 57370
const LCURLY = 57371
const RCURLY = 57372
const LPAREN = 57373
const RPAREN = 57374
const LBRACK = 57375
const RBRACK = 57376
const SEMI = 57377
const COMMA = 57378
const COLON = 57379
const AT = 57380
const DOT = 57381
const ELLIPSIS = 57382
const ASSIGN = 57383
const QUESTION = 57384
const EQ = 57385
const NEQ = 57386
const LEQ = 57387
const GEQ = 57388
const LT = 57389
const GT = 57390
const AND = 57391
const OR = 57392
const IMPL = 57393
const UPDATE = 57394
const CONCAT = 57395
const PLUS = 57396
const MINUS = 57397
const TIMES = 57398
const SLASH = 57399
const NOT = 57400
const NEGATE = 57401

var nixToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"INT",
	"FLOAT",
	"IDENT",
	"STR",
	"ESTR",
	"PATH",
	"SPATH",
	"URI_LIT",
	"PATH_START",
	"PATH_STR",
	"PATH_END",
	"IF",
	"THEN",
	"ELSE",
	"ASSERT",
	"WITH",
	"LET",
	"IN",
	"REC",
	"INHERIT",
	"OR_KW",
	"DQUOTE",
	"IND_OPEN",
	"IND_CLOSE",
	"DOLLAR_CURLY",
	"LCURLY",
	"RCURLY",
	"LPAREN",
	"RPAREN",
	"LBRACK",
	"RBRACK",
	"SEMI",
	"COMMA",
	"COLON",
	"AT",
	"DOT",
	"ELLIPSIS",
	"ASSIGN",
	"QUESTION",
	"EQ",
	"NEQ",
	"LEQ",
	"GEQ",
	"LT",
	"GT",
	"AND",
	"OR",
	"IMPL",
	"UPDATE",
	"CONCAT",
	"PLUS",
	"MINUS",
	"TIMES",
	"SLASH",
	"NOT",
	"NEGATE",
}

var nixStatenames = [...]string{}

const nixEofCode = 1
const nixErrCode = 2
const nixInitialStackSize = 16

//line grammar.y:241

//line yacctab:1
var nixExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 52,
	39, 73,
	41, 73,
	-2, 83,
	-1, 111,
	43, 0,
	44, 0,
	-2, 18,
	-1, 112,
	43, 0,
	44, 0,
	-2, 19,
	-1, 113,
	45, 0,
	46, 0,
	47, 0,
	48, 0,
	-2, 20,
	-1, 114,
	45, 0,
	46, 0,
	47, 0,
	48, 0,
	-2, 21,
	-1, 115,
	45, 0,
	46, 0,
	47, 0,
	48, 0,
	-2, 22,
	-1, 116,
	45, 0,
	46, 0,
	47, 0,
	48, 0,
	-2, 23,
}

const nixPrivate = 57344

const nixLast = 346

var nixAct = [...]uint8{
	38, 2, 6, 159, 42, 99, 51, 40, 17, 36,
	37, 85, 69, 109, 53, 98, 102, 73, 73, 73,
	69, 39, 76, 64, 77, 75, 67, 68, 78, 83,
	142, 64, 73, 47, 89, 34, 35, 141, 86, 69,
	54, 55, 58, 59, 56, 57, 101, 3, 104, 63,
	64, 65, 66, 67, 68, 82, 139, 73, 73, 73,
	73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
	73, 73, 13, 138, 103, 32, 33, 126, 87, 140,
	91, 182, 93, 132, 127, 135, 169, 70, 74, 73,
	140, 30, 31, 147, 47, 86, 96, 95, 137, 136,
	146, 171, 148, 153, 43, 69, 101, 149, 130, 131,
	150, 156, 157, 154, 48, 155, 64, 65, 66, 67,
	68, 41, 44, 45, 49, 134, 46, 111, 112, 113,
	114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
	124, 125, 69, 143, 144, 145, 5, 181, 170, 172,
	43, 164, 63, 64, 65, 66, 67, 68, 161, 160,
	107, 73, 163, 152, 176, 175, 108, 174, 44, 45,
	178, 128, 46, 162, 133, 180, 101, 179, 88, 106,
	105, 79, 80, 184, 90, 183, 165, 166, 84, 167,
	168, 151, 177, 19, 20, 4, 129, 158, 21, 23,
	24, 22, 81, 97, 12, 173, 110, 7, 8, 9,
	94, 28, 92, 50, 25, 26, 1, 18, 11, 16,
	27, 10, 29, 69, 54, 55, 58, 59, 56, 57,
	60, 61, 62, 63, 64, 65, 66, 67, 68, 0,
	52, 0, 0, 0, 15, 0, 0, 14, 19, 20,
	71, 0, 0, 21, 23, 24, 22, 41, 44, 45,
	0, 0, 46, 0, 48, 0, 28, 0, 0, 25,
	26, 0, 0, 72, 49, 27, 43, 29, 69, 54,
	55, 58, 59, 56, 57, 60, 0, 0, 63, 64,
	65, 66, 67, 68, 44, 45, 0, 0, 46, 15,
	69, 100, 14, 58, 59, 56, 57, 0, 43, 0,
	63, 64, 65, 66, 67, 68, 19, 20, 71, 0,
	0, 21, 23, 24, 22, 41, 44, 45, 0, 0,
	46, 0, 48, 0, 28, 0, 0, 25, 26, 0,
	0, 72, 0, 27, 0, 29,
}

var nixPact = [...]int16{
	189, -1000, -1000, -1000, 54, 38, -2, 189, 189, 98,
	-1000, 234, 189, 181, 244, 244, 312, -1000, -17, -1000,
	-1000, -1000, 189, -1000, -1000, 174, 174, 189, 159, 312,
	189, 155, 189, 206, 189, 204, 62, 61, 182, -1000,
	-26, 270, -23, -1000, -1000, 174, 189, 150, -1000, 149,
	130, -1000, -29, 190, 244, 244, 244, 244, 244, 244,
	244, 244, 244, 244, 244, 244, 244, 244, 244, 144,
	63, -1000, 302, -1000, -1000, -1000, 144, 141, 171, 174,
	174, 189, 147, 93, 98, 65, 312, -1000, 36, 19,
	84, -1000, 0, -1000, -7, 189, 189, 189, 189, 58,
	189, 144, 144, 166, 133, -1000, -1000, -1000, 73, 189,
	189, 258, 258, 100, 100, 100, 100, -3, 236, 181,
	100, -22, -30, -30, -22, -22, -1000, 173, 145, -1000,
	-1000, -1000, 132, -1000, -1000, 121, -1000, -1000, 189, 189,
	-29, 189, 189, -1000, -1000, -1000, 51, 98, 69, -1000,
	-1000, -1000, -1000, -1000, 119, -1000, -1000, 188, 312, -1000,
	-1000, 145, 189, 174, -1000, -1000, -1000, -1000, -1000, 98,
	-1000, 144, -1000, 189, -1000, -1000, 117, -1000, -1000, 46,
	-1000, 145, 98, -1000, -1000,
}

var nixPgo = [...]uint8{
	0, 1, 47, 221, 72, 219, 8, 217, 216, 11,
	28, 3, 4, 5, 7, 0, 21, 146, 6, 213,
	2,
}

var nixR1 = [...]int8{
	0, 8, 1, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 3, 3, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 5, 5, 6, 6, 6,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 11, 11, 11, 10, 10, 10,
	10, 9, 9, 20, 15, 15, 16, 16, 16, 13,
	13, 14, 14, 12, 12, 12, 12, 17, 17, 17,
	17, 19, 19, 18, 18,
}

var nixR2 = [...]int8{
	0, 1, 1, 3, 3, 5, 5, 3, 5, 5,
	4, 4, 4, 1, 6, 1, 2, 2, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 1, 2, 1, 3, 5, 1,
	1, 1, 1, 1, 4, 1, 1, 3, 3, 3,
	4, 3, 1, 3, 1, 2, 4, 0, 2, 2,
	4, 0, 2, 2, 0, 1, 5, 4, 7, 0,
	2, 1, 3, 1, 1, 3, 3, 3, 3, 4,
	5, 1, 3, 1, 3,
}

var nixChk = [...]int16{
	-1000, -8, -1, -2, 6, -17, -20, 18, 19, 20,
	-3, 29, 15, -4, 58, 55, -5, -6, -7, 4,
	5, 9, 12, 10, 11, 25, 26, 31, 22, 33,
	37, 38, 37, 38, 37, 38, -1, -1, -15, -16,
	-14, 23, -12, 6, 24, 25, 28, -16, 30, 40,
	-19, -18, 6, -1, 43, 44, 47, 48, 45, 46,
	49, 50, 51, 52, 53, 54, 55, 56, 57, 42,
	-4, 6, 29, -20, -4, -6, 39, -1, -10, 7,
	8, 28, -10, -1, 29, -9, -6, -2, -17, -20,
	29, -2, 6, -2, 6, 35, 35, 21, 41, -13,
	31, -12, 39, -10, -1, 30, 30, 30, 36, 42,
	16, -4, -4, -4, -4, -4, -4, -4, -4, -4,
	-4, -4, -4, -4, -4, -4, -14, -14, 30, 25,
	-10, -10, -1, 27, 32, -15, 34, -9, 37, 37,
	6, 37, 37, -2, -2, -2, -1, 35, -1, -13,
	-14, 25, 30, 30, 40, -18, -1, -1, 24, -11,
	14, 13, 28, 30, 30, -2, -2, -2, -2, 35,
	-15, 32, 30, 17, -6, -11, -1, -10, -15, -13,
	-1, 30, 35, -11, -15,
}

var nixDef = [...]int8{
	0, -2, 1, 2, 40, 0, 52, 0, 0, 64,
	13, 0, 0, 15, 0, 0, 34, 36, 39, 41,
	42, 43, 0, 45, 46, 57, 57, 0, 0, 61,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 65,
	0, 69, 71, 73, 74, 57, 0, 0, 63, 0,
	0, 81, -2, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	16, 40, 0, 52, 17, 35, 0, 0, 0, 57,
	57, 0, 0, 0, 64, 0, 61, 3, 0, 0,
	0, 4, 0, 7, 0, 0, 0, 0, 0, 0,
	0, 69, 0, 0, 0, 51, 77, 78, 0, 0,
	0, -2, -2, -2, -2, -2, -2, 24, 25, 26,
	27, 28, 29, 30, 31, 32, 33, 37, 0, 47,
	58, 59, 0, 48, 49, 0, 53, 62, 0, 0,
	83, 0, 0, 10, 11, 12, 0, 64, 0, 70,
	72, 75, 76, 79, 0, 82, 84, 0, 0, 44,
	54, 0, 0, 57, 50, 6, 9, 5, 8, 64,
	67, 69, 80, 0, 38, 55, 0, 60, 66, 0,
	14, 0, 64, 56, 68,
}

var nixTok1 = [...]int8{
	1,
}

var nixTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59,
}

var nixTok3 = [...]int8{
	0,
}

var nixErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	nixDebug        = 0
	nixErrorVerbose = false
)

type nixLexer interface {
	Lex(lval *nixSymType) int
	Error(s string)
}

type nixParser interface {
	Parse(nixLexer) int
	Lookahead() int
}

type nixParserImpl struct {
	lval  nixSymType
	stack [nixInitialStackSize]nixSymType
	char  int
}

func (p *nixParserImpl) Lookahead() int {
	return p.char
}

func nixNewParser() nixParser {
	return &nixParserImpl{}
}

const nixFlag = -1000

func nixTokname(c int) string {
	if c >= 1 && c-1 < len(nixToknames) {
		if nixToknames[c-1] != "" {
			return nixToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func nixStatname(s int) string {
	if s >= 0 && s < len(nixStatenames) {
		if nixStatenames[s] != "" {
			return nixStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func nixErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !nixErrorVerbose {
		return "syntax error"
	}

	for _, e := range nixErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + nixTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(nixPact[state])
	for tok := TOKSTART; tok-1 < len(nixToknames); tok++ {
		if n := base + tok; n >= 0 && n < nixLast && int(nixChk[int(nixAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if nixDef[state] == -2 {
		i := 0
		for nixExca[i] != -1 || int(nixExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; nixExca[i] >= 0; i += 2 {
			tok := int(nixExca[i])
			if tok < TOKSTART || nixExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if nixExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += nixTokname(tok)
	}
	return res
}

func nixlex1(lex nixLexer, lval *nixSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(nixTok1[0])
		goto out
	}
	if char < len(nixTok1) {
		token = int(nixTok1[char])
		goto out
	}
	if char >= nixPrivate {
		if char < nixPrivate+len(nixTok2) {
			token = int(nixTok2[char-nixPrivate])
			goto out
		}
	}
	for i := 0; i < len(nixTok3); i += 2 {
		token = int(nixTok3[i+0])
		if token == char {
			token = int(nixTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(nixTok2[1]) /* unknown char */
	}
	if nixDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", nixTokname(token), uint(char))
	}
	return char, token
}

func nixParse(nixlex nixLexer) int {
	return nixNewParser().Parse(nixlex)
}

func (nixrcvr *nixParserImpl) Parse(nixlex nixLexer) int {
	var nixn int
	var nixVAL nixSymType
	var nixDollar []nixSymType
	_ = nixDollar // silence set and not used
	nixS := nixrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	nixstate := 0
	nixrcvr.char = -1
	nixtoken := -1 // nixrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		nixstate = -1
		nixrcvr.char = -1
		nixtoken = -1
	}()
	nixp := -1
	goto nixstack

ret0:
	return 0

ret1:
	return 1

nixstack:
	/* put a state and value onto the stack */
	if nixDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", nixTokname(nixtoken), nixStatname(nixstate))
	}

	nixp++
	if nixp >= len(nixS) {
		nyys := make([]nixSymType, len(nixS)*2)
		copy(nyys, nixS)
		nixS = nyys
	}
	nixS[nixp] = nixVAL
	nixS[nixp].yys = nixstate

nixnewstate:
	nixn = int(nixPact[nixstate])
	if nixn <= nixFlag {
		goto nixdefault /* simple state */
	}
	if nixrcvr.char < 0 {
		nixrcvr.char, nixtoken = nixlex1(nixlex, &nixrcvr.lval)
	}
	nixn += nixtoken
	if nixn < 0 || nixn >= nixLast {
		goto nixdefault
	}
	nixn = int(nixAct[nixn])
	if int(nixChk[nixn]) == nixtoken { /* valid shift */
		nixrcvr.char = -1
		nixtoken = -1
		nixVAL = nixrcvr.lval
		nixstate = nixn
		if Errflag > 0 {
			Errflag--
		}
		goto nixstack
	}

nixdefault:
	/* default state action */
	nixn = int(nixDef[nixstate])
	if nixn == -2 {
		if nixrcvr.char < 0 {
			nixrcvr.char, nixtoken = nixlex1(nixlex, &nixrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if nixExca[xi+0] == -1 && int(nixExca[xi+1]) == nixstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			nixn = int(nixExca[xi+0])
			if nixn < 0 || nixn == nixtoken {
				break
			}
		}
		nixn = int(nixExca[xi+1])
		if nixn < 0 {
			goto ret0
		}
	}
	if nixn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			nixlex.Error(nixErrorMessage(nixstate, nixtoken))
			Nerrs++
			if nixDebug >= 1 {
				__yyfmt__.Printf("%s", nixStatname(nixstate))
				__yyfmt__.Printf(" saw %s\n", nixTokname(nixtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for nixp >= 0 {
				nixn = int(nixPact[nixS[nixp].yys]) + nixErrCode
				if nixn >= 0 && nixn < nixLast {
					nixstate = int(nixAct[nixn]) /* simulate a shift of "error" */
					if int(nixChk[nixstate]) == nixErrCode {
						goto nixstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if nixDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", nixS[nixp].yys)
				}
				nixp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if nixDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", nixTokname(nixtoken))
			}
			if nixtoken == nixEofCode {
				goto ret1
			}
			nixrcvr.char = -1
			nixtoken = -1
			goto nixnewstate /* try again in the same state */
		}
	}

	/* reduction by production nixn */
	if nixDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", nixn, nixStatname(nixstate))
	}

	nixnt := nixn
	nixpt := nixp
	_ = nixpt // guard against "declared and not used"

	nixp -= int(nixR2[nixn])
	// nixp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if nixp+1 >= len(nixS) {
		nyys := make([]nixSymType, len(nixS)*2)
		copy(nyys, nixS)
		nixS = nyys
	}
	nixVAL = nixS[nixp+1]

	/* consult goto table to find next state */
	nixn = int(nixR1[nixn])
	nixg := int(nixPgo[nixn])
	nixj := nixg + nixS[nixp].yys + 1

	if nixj >= nixLast {
		nixstate = int(nixAct[nixg])
	} else {
		nixstate = int(nixAct[nixj])
		if int(nixChk[nixstate]) != -nixn {
			nixstate = int(nixAct[nixg])
		}
	}
	// dummy call; replaced with literal code
	switch nixnt {

	case 1:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:89
		{
			nixVAL.expr = nixDollar[1].expr
			nixlex.(*Lexer).result = nixDollar[1].expr
		}
	case 2:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:92
		{
			nixVAL.expr = nixDollar[1].expr
		}
	case 3:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:95
		{
			nixVAL.expr = Lambda{Pattern: PVar{Name: nixDollar[1].str}, Body: nixDollar[3].expr}
		}
	case 4:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:96
		{
			nixVAL.expr = Lambda{Pattern: nixDollar[1].pattern, Body: nixDollar[3].expr}
		}
	case 5:
		nixDollar = nixS[nixpt-5 : nixpt+1]
//line grammar.y:97
		{
			nixVAL.expr = Lambda{Pattern: withAlias(nixDollar[1].pattern, nixDollar[3].str), Body: nixDollar[5].expr}
		}
	case 6:
		nixDollar = nixS[nixpt-5 : nixpt+1]
//line grammar.y:98
		{
			nixVAL.expr = Lambda{Pattern: withAlias(nixDollar[3].pattern, nixDollar[1].str), Body: nixDollar[5].expr}
		}
	case 7:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:104
		{
			nixVAL.expr = Lambda{Pattern: PSet{}, Body: nixDollar[3].expr}
		}
	case 8:
		nixDollar = nixS[nixpt-5 : nixpt+1]
//line grammar.y:105
		{
			nixVAL.expr = Lambda{Pattern: PSet{Alias: nixDollar[3].str}, Body: nixDollar[5].expr}
		}
	case 9:
		nixDollar = nixS[nixpt-5 : nixpt+1]
//line grammar.y:106
		{
			nixVAL.expr = Lambda{Pattern: PSet{Alias: nixDollar[1].str}, Body: nixDollar[5].expr}
		}
	case 10:
		nixDollar = nixS[nixpt-4 : nixpt+1]
//line grammar.y:107
		{
			nixVAL.expr = Assert{Condition: nixDollar[2].expr, Body: nixDollar[4].expr}
		}
	case 11:
		nixDollar = nixS[nixpt-4 : nixpt+1]
//line grammar.y:108
		{
			nixVAL.expr = With{Scope: nixDollar[2].expr, Body: nixDollar[4].expr}
		}
	case 12:
		nixDollar = nixS[nixpt-4 : nixpt+1]
//line grammar.y:109
		{
			nixVAL.expr = Let{Binds: nixDollar[2].binds, Body: nixDollar[4].expr}
		}
	case 13:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:110
		{
			nixVAL.expr = nixDollar[1].expr
		}
	case 14:
		nixDollar = nixS[nixpt-6 : nixpt+1]
//line grammar.y:113
		{
			nixVAL.expr = If{Condition: nixDollar[2].expr, Then: nixDollar[4].expr, Else: nixDollar[6].expr}
		}
	case 15:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:114
		{
			nixVAL.expr = nixDollar[1].expr
		}
	case 16:
		nixDollar = nixS[nixpt-2 : nixpt+1]
//line grammar.y:117
		{
			nixVAL.expr = Not{Expr: nixDollar[2].expr}
		}
	case 17:
		nixDollar = nixS[nixpt-2 : nixpt+1]
//line grammar.y:118
		{
			nixVAL.expr = Neg{Expr: nixDollar[2].expr}
		}
	case 18:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:119
		{
			nixVAL.expr = BinOp{Op: OpEq, Left: nixDollar[1].expr, Right: nixDollar[3].expr}
		}
	case 19:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:120
		{
			nixVAL.expr = BinOp{Op: OpNeq, Left: nixDollar[1].expr, Right: nixDollar[3].expr}
		}
	case 20:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:121
		{
			nixVAL.expr = BinOp{Op: OpLt, Left: nixDollar[1].expr, Right: nixDollar[3].expr}
		}
	case 21:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:122
		{
			nixVAL.expr = BinOp{Op: OpGt, Left: nixDollar[1].expr, Right: nixDollar[3].expr}
		}
	case 22:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:123
		{
			nixVAL.expr = BinOp{Op: OpLe, Left: nixDollar[1].expr, Right: nixDollar[3].expr}
		}
	case 23:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:124
		{
			nixVAL.expr = BinOp{Op: OpGe, Left: nixDollar[1].expr, Right: nixDollar[3].expr}
		}
	case 24:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:125
		{
			nixVAL.expr = BinOp{Op: OpAnd, Left: nixDollar[1].expr, Right: nixDollar[3].expr}
		}
	case 25:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:126
		{
			nixVAL.expr = BinOp{Op: OpOr, Left: nixDollar[1].expr, Right: nixDollar[3].expr}
		}
	case 26:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:127
		{
			nixVAL.expr = BinOp{Op: OpImpl, Left: nixDollar[1].expr, Right: nixDollar[3].expr}
		}
	case 27:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:128
		{
			nixVAL.expr = BinOp{Op: OpUpdate, Left: nixDollar[1].expr, Right: nixDollar[3].expr}
		}
	case 28:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:129
		{
			nixVAL.expr = BinOp{Op: OpConcat, Left: nixDollar[1].expr, Right: nixDollar[3].expr}
		}
	case 29:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:130
		{
			nixVAL.expr = BinOp{Op: OpAdd, Left: nixDollar[1].expr, Right: nixDollar[3].expr}
		}
	case 30:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:131
		{
			nixVAL.expr = BinOp{Op: OpSub, Left: nixDollar[1].expr, Right: nixDollar[3].expr}
		}
	case 31:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:132
		{
			nixVAL.expr = BinOp{Op: OpMul, Left: nixDollar[1].expr, Right: nixDollar[3].expr}
		}
	case 32:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:133
		{
			nixVAL.expr = BinOp{Op: OpDiv, Left: nixDollar[1].expr, Right: nixDollar[3].expr}
		}
	case 33:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:134
		{
			nixVAL.expr = HasAttr{Expr: nixDollar[1].expr, Path: nixDollar[3].path}
		}
	case 34:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:135
		{
			nixVAL.expr = nixDollar[1].expr
		}
	case 35:
		nixDollar = nixS[nixpt-2 : nixpt+1]
//line grammar.y:138
		{
			nixVAL.expr = Apply{Func: nixDollar[1].expr, Arg: nixDollar[2].expr}
		}
	case 36:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:139
		{
			nixVAL.expr = nixDollar[1].expr
		}
	case 37:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:142
		{
			nixVAL.expr = Select{Expr: nixDollar[1].expr, Path: nixDollar[3].path}
		}
	case 38:
		nixDollar = nixS[nixpt-5 : nixpt+1]
//line grammar.y:143
		{
			nixVAL.expr = Select{Expr: nixDollar[1].expr, Path: nixDollar[3].path, Default: nixDollar[5].expr}
		}
	case 39:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:144
		{
			nixVAL.expr = nixDollar[1].expr
		}
	case 40:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:147
		{
			nixVAL.expr = Var{Name: nixDollar[1].str}
		}
	case 41:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:148
		{
			nixVAL.expr = Int{Value: nixDollar[1].num}
		}
	case 42:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:149
		{
			nixVAL.expr = Float{Value: nixDollar[1].fnum}
		}
	case 43:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:150
		{
			nixVAL.expr = PathLit{Text: ResolvePath(nixDollar[1].str)}
		}
	case 44:
		nixDollar = nixS[nixpt-4 : nixpt+1]
//line grammar.y:153
		{
			parts := []Part{Anti{Expr: PathLit{Text: ResolvePathPrefix(nixDollar[1].str)}}, Anti{Expr: nixDollar[2].expr}}
			nixVAL.expr = PathInterp{Parts: append(parts, nixDollar[4].parts...)}
		}
	case 45:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:157
		{
			nixVAL.expr = SearchPath{Text: nixDollar[1].str}
		}
	case 46:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:158
		{
			nixVAL.expr = URI{Text: nixDollar[1].str}
		}
	case 47:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:159
		{
			nixVAL.expr = Str{Parts: dropEmpty(plainParts(nixDollar[2].iparts))}
		}
	case 48:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:162
		{
			stripped := StripIndentation(nixDollar[2].iparts)
			if len(stripped) == 1 {
				if _, ok := stripped[0].(Lit); ok {
					nixVAL.expr = Str{Parts: stripped}
				} else {
					nixVAL.expr = IndStr{Parts: stripped}
				}
			} else {
				nixVAL.expr = IndStr{Parts: stripped}
			}
		}
	case 49:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:174
		{
			nixVAL.expr = nixDollar[2].expr
		}
	case 50:
		nixDollar = nixS[nixpt-4 : nixpt+1]
//line grammar.y:175
		{
			nixVAL.expr = AttrSet{Recursive: true, Binds: nixDollar[3].binds}
		}
	case 51:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:176
		{
			nixVAL.expr = AttrSet{Binds: nixDollar[2].binds}
		}
	case 52:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:177
		{
			nixVAL.expr = AttrSet{}
		}
	case 53:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:178
		{
			nixVAL.expr = List{Items: nixDollar[2].exprs}
		}
	case 54:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:181
		{
			nixVAL.parts = nil
		}
	case 55:
		nixDollar = nixS[nixpt-2 : nixpt+1]
//line grammar.y:182
		{
			nixVAL.parts = append([]Part{Lit{Text: nixDollar[1].str}}, nixDollar[2].parts...)
		}
	case 56:
		nixDollar = nixS[nixpt-4 : nixpt+1]
//line grammar.y:183
		{
			nixVAL.parts = append([]Part{Anti{Expr: nixDollar[2].expr}}, nixDollar[4].parts...)
		}
	case 57:
		nixDollar = nixS[nixpt-0 : nixpt+1]
//line grammar.y:186
		{
			nixVAL.iparts = nil
		}
	case 58:
		nixDollar = nixS[nixpt-2 : nixpt+1]
//line grammar.y:187
		{
			nixVAL.iparts = append([]indexedPart{{Part: Lit{Text: nixDollar[1].str}, Indented: true}}, nixDollar[2].iparts...)
		}
	case 59:
		nixDollar = nixS[nixpt-2 : nixpt+1]
//line grammar.y:188
		{
			nixVAL.iparts = append([]indexedPart{{Part: Lit{Text: nixDollar[1].str}}}, nixDollar[2].iparts...)
		}
	case 60:
		nixDollar = nixS[nixpt-4 : nixpt+1]
//line grammar.y:189
		{
			nixVAL.iparts = append([]indexedPart{{Part: Anti{Expr: nixDollar[2].expr}}}, nixDollar[4].iparts...)
		}
	case 61:
		nixDollar = nixS[nixpt-0 : nixpt+1]
//line grammar.y:192
		{
			nixVAL.exprs = nil
		}
	case 62:
		nixDollar = nixS[nixpt-2 : nixpt+1]
//line grammar.y:193
		{
			nixVAL.exprs = append([]Expr{nixDollar[1].expr}, nixDollar[2].exprs...)
		}
	case 63:
		nixDollar = nixS[nixpt-2 : nixpt+1]
//line grammar.y:196
		{
		}
	case 64:
		nixDollar = nixS[nixpt-0 : nixpt+1]
//line grammar.y:199
		{
			nixVAL.binds = nil
		}
	case 65:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:200
		{
			nixVAL.binds = nixDollar[1].binds
		}
	case 66:
		nixDollar = nixS[nixpt-5 : nixpt+1]
//line grammar.y:203
		{
			nixVAL.binds = append([]Binding{Bind{Path: nixDollar[1].path, Value: nixDollar[3].expr}}, nixDollar[5].binds...)
		}
	case 67:
		nixDollar = nixS[nixpt-4 : nixpt+1]
//line grammar.y:204
		{
			nixVAL.binds = append([]Binding{Inherit{Attrs: nixDollar[2].attrs}}, nixDollar[4].binds...)
		}
	case 68:
		nixDollar = nixS[nixpt-7 : nixpt+1]
//line grammar.y:205
		{
			nixVAL.binds = append([]Binding{Inherit{Source: nixDollar[3].expr, Attrs: nixDollar[5].attrs}}, nixDollar[7].binds...)
		}
	case 69:
		nixDollar = nixS[nixpt-0 : nixpt+1]
//line grammar.y:210
		{
			nixVAL.attrs = nil
		}
	case 70:
		nixDollar = nixS[nixpt-2 : nixpt+1]
//line grammar.y:211
		{
			nixVAL.attrs = append([]Attr{nixDollar[1].attr}, nixDollar[2].attrs...)
		}
	case 71:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:214
		{
			nixVAL.path = AttrPath{nixDollar[1].attr}
		}
	case 72:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:215
		{
			nixVAL.path = append(AttrPath{nixDollar[1].attr}, nixDollar[3].path...)
		}
	case 73:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:218
		{
			nixVAL.attr = ID{Name: nixDollar[1].str}
		}
	case 74:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:219
		{
			nixVAL.attr = ID{Name: "or"}
		}
	case 75:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:220
		{
			nixVAL.attr = StrAttr{Parts: dropEmpty(plainParts(nixDollar[2].iparts))}
		}
	case 76:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:221
		{
			nixVAL.attr = DynAttr{Expr: nixDollar[2].expr}
		}
	case 77:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:226
		{
			nixVAL.pattern = PSet{Ellipsis: true}
		}
	case 78:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:227
		{
			nixVAL.pattern = PSet{Formals: nixDollar[2].formals}
		}
	case 79:
		nixDollar = nixS[nixpt-4 : nixpt+1]
//line grammar.y:228
		{
			nixVAL.pattern = PSet{Formals: nixDollar[2].formals}
		}
	case 80:
		nixDollar = nixS[nixpt-5 : nixpt+1]
//line grammar.y:229
		{
			nixVAL.pattern = PSet{Formals: nixDollar[2].formals, Ellipsis: true}
		}
	case 81:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:234
		{
			nixVAL.formals = []Formal{nixDollar[1].formal}
		}
	case 82:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:235
		{
			nixVAL.formals = append(nixDollar[1].formals, nixDollar[3].formal)
		}
	case 83:
		nixDollar = nixS[nixpt-1 : nixpt+1]
//line grammar.y:238
		{
			nixVAL.formal = Formal{Name: nixDollar[1].str}
		}
	case 84:
		nixDollar = nixS[nixpt-3 : nixpt+1]
//line grammar.y:239
		{
			nixVAL.formal = Formal{Name: nixDollar[1].str, Default: nixDollar[3].expr}
		}
	}
	goto nixstack /* stack new state and value */
}
